### ISSUE TITLE
Two more insights

### ISSUE THREAD

**Issue by AlekseyMartynov** [marin-m/SongRec#10]
Hello

I'd like to share two more insights that I got, that helped me better understand the signature format.

### Bin interpolation
https://github.com/marin-m/SongRec/blob/0aa3a32d54287195becb46e2bf3865ef5efeebf5/src/fingerprinting/algorithm.rs#L239-L242

This is precisely Quadratic Interpolation of Spectral Peaks described very well in https://ccrma.stanford.edu/~jos/sasp/Quadratic_Interpolation_Spectral_Peaks.html. They also suggest an interpolation formula for magnitude. And I guess this is what is refered to as 'curvature' in the binary.

### Magnitude scaling
https://github.com/marin-m/SongRec/blob/0aa3a32d54287195becb46e2bf3865ef5efeebf5/src/fingerprinting/algorithm.rs#L235

Empirically, I found that the exact expression is 
```
3 * 4096 * (log(m) / log(64) - 1)
```
where `m` is clean magnitude (i.e. without scaling and squaring), and 64 happens to be the minimum value that yields non negative results.

It seems to me that here
https://github.com/marin-m/SongRec/blob/0aa3a32d54287195becb46e2bf3865ef5efeebf5/src/fingerprinting/algorithm.rs#L136-L141
the divider should be `1 << 18` to match the formula. Surely, it doesn't affect the recognition. Just found it interesting to share.

Cheers

**Comment by marin-m** [comment]
Hello,

>It seems to me that here the divider should be `1 << 18` to match the formula.

Code actually does the equivalent of dividing by `1 << 17` in the original thing (which is probably the compiler-optimized version of doing `/ 2048 / 64`).

I don't know however why it's doing a natural logarithm over the summed up squared real and imaginary parts of the complex, instead of a square root like magnitude calculation would require. I guess that it's a way to both make the resulting output fit in a 16-bit integer, and very roughly approximate human hearing which is logarithmic, while staying computationally efficient.

>Empirically, I found that the exact expression is
>
>```
>3 * 4096 * (log(m) / log(64) - 1)
>```
>
>where m is clean magnitude (i.e. without scaling and squaring), and 64 happens to be the minimum value that yields non negative results.

It seems that this expression:

```rust
let peak_magnitude: f32 = fft_minus_46[bin_position].ln().max(1.0 / 64.0) * 1477.3 + 6144.0; 
```

Is actually equivalent to:

```rust
let log_bin: f32 = fft_minus_46[bin_position].ln().max(1.0 / 64.0);
let peak_magnitude: f32 = (log_bin / (64_f32).ln() + 1.0) * 3.0 * 2048.0; 
```

As it can be verified through:

```python
>>> 3 * 2048
6144
>>> (3 * 2048) / log(64)
1477.3197218702987

>>> 1 * 1477.31970215 + 6144.0
7621.31970215
>>> 1 * ((1.5 * 4096) / log(64)) + (3 * 2048)
7621.319721870299
>>> 1 * (1.5 * 4096) / log(64) + (3 * 2048)
7621.319721870299
>>> (1 / log(64) + 1) * (3 * 2048)
7621.319721870299
```

It is likely that it is the product of compiler optimization and constant definition of the `log(64)` value.

Regards,

**Comment by AlekseyMartynov** [comment]
My concern was exactly the difference between `1 << 17` in your code and `1 << 18` which I got during my experiments.

Let me try to explain my way of thinking.

I analyzed signatures produced by Shazam for Android. For this, I used [x86 ARM emulator](https://developer.android.com/studio/releases/emulator#support_for_arm_binaries_on_android_9_and_11_system_images) + [VB-Audio virtual device](https://vb-audio.com/Cable/index.htm) to feed a predefined piece of sound to Shazam. With a disconnected network, the app stores offline signatures of good length in the database from which they can be easily extracted. By aligning peaks with my own implementation and doing linear regression, I came up with the formula:

```
3 * 4096 * (log(m) / log(64) - 1)
```

The use of logarithm may be related to human hearing, as you suggest, but also it packs a wide range of magnitudes into unsigned 16 bit integer.

Suppose, instead of the magnitude `m`, I'm using 

```
x = m * m / (1 << 18)
```

which is equivalent to 

```
x = m * m / 64 / 64 / 64
```

Squared `m` has a good rationale of saving on taking square roots. As for scaling, I don't see any obvious advantages of doing it right here.

If I substitute `m` with `x`, then I get the formula from your sources:

```
m = (64 * 64 * 64 * x)^(1/2)

3 * 4096 * ( (1/2) * (log(64) + log(64) + log(64) + log(x)) / log(64) - 1 )

3 * 4096 * ( 1/2 + 1/2 + 1/2 + 1/2 * (log(x) / log(64)) - 1)

3 * 4096 * (             1/2 + 1/2 * (log(x) / log(64))    )

3 * 2048 * (1 + log(x) / log(64))

6144 + 1477.3 * log(x)
```

Note that we now have a good formal explanation for this check:
https://github.com/marin-m/SongRec/blob/0aa3a32d54287195becb46e2bf3865ef5efeebf5/src/fingerprinting/algorithm.rs#L198

`x = 1/64` is equivalent to `m = 64` which is the minimum value that yields non-negative results suitable for unsigned data type. Also, you won't need to repeat this check as `.max()` in
https://github.com/marin-m/SongRec/blob/0aa3a32d54287195becb46e2bf3865ef5efeebf5/src/fingerprinting/algorithm.rs#L235


For completeness, below are the results of linear regression tests that I mentioned above:

Mine vs Android v6
```
y=1.0056x-231.9803
y=1.0045x-211.4566
```

Mine vs ShazamCore.dll
```
y=1.0042x-204.6618
```

Mine vs Android v11
```
y=1.0071x+741.3564
y=1.0091x+687.1829
```

Mine vs SongRec w/o modifications
```
y=0.9878x+1246.1194
```

Mine vs SongRec with `1 << 18` - **note the smaller constant**
```
y=0.9878x+222.1273
```

--

Phew, what an exercise 😄

**Comment by marin-m** [comment]
I performed the analysis on the required parts of the code mostly using static means (Hex-Rays/IDA for the binary part, and some JD-Gui for the other side of the binary interface). Obviously the annotated code can't be legally shared due to intellectual property reasons.

I completed the procedure with some dynamic verification (a. using mitmproxy+Wireshark over an Android device for verifying the produced network output and signatures, b. additionally cross-compiling some `dlopen`-based code for communicating with the binary interface directly and debugging the behavior with `gdb` when I wasn't sure about register values), but completed it when the obtained values from the `binary` interface were near enough with the same input settings.

Regarding the differences observed using your audio simulation software, it can be though out whether system input volume, alignment of the input time points, sample rates, system API differences, etc.

**Comment by AlekseyMartynov** [comment]
The results of your analysis can be 100% accurate. By no means I'm arguing with that. What I say is that the use of the `1 << 18` divider makes the entire algorithm more consistent and self-explaining.

**Comment by AlekseyMartynov** [comment]
Here are some extras. I checked older APKs and found an interesting point between versions `7.10.3` and `7.11.0`.

### Older versions
The binary is named `libShazamMRE`

Regression:
```
y=1.0010x-51.7615
y=1.0073x-225.2951
y=1.0008x-48.4272
```
The constant is negative approx between -50 and -250

Code analysis reveals expressions that I kind of like:
![code](https://user-images.githubusercontent.com/4426185/99870935-c48dd000-2be7-11eb-8fd6-4d83381c324d.png)

### Newer versions
The binary is `libsigx`

Regression:
```
// v7.11
y=1.0038x+839.2133
y=1.0040x+836.5134
y=1.0041x+833.1110
// v11
y=1.0071x+741.3564
y=1.0091x+687.1829
y=1.0045x+801.2228
```
The constant is positive somewhere around 700-800

By the way, I'm pretty sure that the input volume and the environment are stable, because it is the same emulator session and I don't touch any faders 😄 

Presudocode:
![code](https://user-images.githubusercontent.com/4426185/99871033-880ea400-2be8-11eb-8e93-2606729900f5.png)

Please note how the numbers differ. Some are doubled, others are halved. Some are under the logarithm.

My hypothesis is that they might have changed scaling, deliberately or due to a refactoring error. This makes me think that scaling is not important. Perhaps, magnitudes are not used at all. I tried to grasp the theory behind their math. You, as I understand it, want to be as close as possible to the recent binary.

Thanks for your involvement!
