### ISSUE TITLE
Fail to install on Ubuntu

### ISSUE THREAD

**Issue by mybuntu-git2** [marin-m/SongRec#106]
After adding the repo and updating:
Expected: we can install songrec with` sudo apt install songrec` as per documentation.
Observed result
`E: Unable to locate package songrec`

**Comment by marin-m** [comment]
Hello,

What was the output of the `sudo apt-add-repository ppa:marin-m/songrec -y -u` command?

Which version of Ubuntu do you use?

Does explicitly running `sudo apt-get update` before trying to install the package from the PPA work and does not fail?

Regards,

**Comment by mybuntu-git2** [comment]
Sorry, I did not add all the required info.
Yes the ppa is added successfully with the command provided, and update shows the ppa being queried ok.
I am running Ubuntu 20.04 on a Raspberry pi 4B (arm64).
For me it would also be ok to have a docker image, but unfortunately I don’t have the skills to contribute in that direction.

**Comment by marin-m** [comment]
Re,

I have enabled building the PPA package for SongRec for other architectures than x86-64, including ARM64 (it was previously disabled because an older version of the CPAL library had trouble building on the x86-32 platform).

Can you please type `sudo apt-get update` and confirm whether the corresponding PPA package is now available for you?

Regards,

**Comment by mybuntu-git2** [comment]
Hi, I tested and it works and also I tested the CLI and get a correct http response.
Thanks for the extremely quick fix!!
