### ISSUE TITLE
SongRec as a lib

### ISSUE THREAD

**Issue by LeanderK** [marin-m/SongRec#15]
As mentioned here https://github.com/marin-m/SongRec/issues/11, I want to use SongRec from python. I never coded in rust, but I set up a small rust wrapper to marshall the types, but I am unable to import anything even though SongRec is in my cradle dependencies (``can't find crate for `songrec` ``).

I think this is due to SongRec not having a lib-section and therefore not exposing anything (first time using rust...)?

**Comment by marin-m** [comment]
Hello,

See here for the purpose of not making a library: #12

You can't import this crate as a library because there is a binary crate. There are two types of crates in Rust, binary crates, which have a `src/main.rs` file and have an entry point other that tests or benchmarks, and library crates which have a `src/lib.rs` file and are importable in other projects.

**Comment by LeanderK** [comment]
ok. Should I close this issue then?

**Comment by marin-m** [comment]
No problem
