### ISSUE TITLE
Add Info to clipboard or at least make it easier to get

### ISSUE THREAD

**Issue by scruffynerf** [marin-m/SongRec#31]
There is currently no easy way to get the recognized info into the clipboard (Linux at least)

It would be helpful if you add this.

**Comment by marin-m** [comment]
Hello,

Following commits a561a65b and a520a8a, the song recognition history now has a right-click context menu that allows to copy the name of the songs, artists, tracks or albums, or to search previously recognized songs on YouTube, and it is now possible to select the name of the last recognized song so that it can be copy-pasted somewhere easily.

Screenshot:

![image](https://user-images.githubusercontent.com/25437947/112643670-e53f8e00-8e44-11eb-9ab4-c5970aa7eb70.png)

These changes will be released as version 0.1.5 which is currently being pushed to distribution channels.

Have a good day
