### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by AlekseyMartynov** [marin-m/SongRec#4]
I wonder how you got to know the signature format. Is this the result of reverse engineering? Or do you have any insider knowledge? Also, do you know anything about alternative signature formats, for example, [the one from the Windows version that I tried to reverse myself](https://github.com/tomer8007/windows-shazam/issues/4#issuecomment-669347150)?

Your project filed all blank spots in my understanding, and I was able to build [my own Shazam client](https://github.com/AlekseyMartynov/shazam-for-real) in .Net.

I learned a few things that I'd like to share with you.

### Signature format

- The [0x94119c00 magic](https://github.com/marin-m/SongRec/blob/8d1d60f70273a19faf0f9941914e150583ad6cac/src/fingerprinting/signature_format.rs#L73) is not necessary. Shazam accepts zero at this offset. Perhaps, it's either optional data or an optional chunk.
- I don't use the [0.24 padding in the 'number of samples field'](https://github.com/marin-m/SongRec/blob/8d1d60f70273a19faf0f9941914e150583ad6cac/src/fingerprinting/signature_format.rs#L77), and it works, too. Are you sure that the factor is always 0.24 or it drifts?

### Peak detection

I found that peak detection can be as simple as scanning for the maximum magnitude within ±48 interval horizontally and vertically. I don't use spreading
https://github.com/marin-m/SongRec/blob/8d1d60f70273a19faf0f9941914e150583ad6cac/src/fingerprinting/algorithm.rs#L149
nor interpolation
https://github.com/marin-m/SongRec/blob/8d1d60f70273a19faf0f9941914e150583ad6cac/src/fingerprinting/algorithm.rs#L239-L242
nor sparse offsets
https://github.com/marin-m/SongRec/blob/8d1d60f70273a19faf0f9941914e150583ad6cac/src/fingerprinting/algorithm.rs#L205
The [related code is very simple](https://github.com/AlekseyMartynov/shazam-for-real/blob/0c6c2523e2258bfe6283e0aaf087836cd49df700/Landmarks.cs#L24-L43). Nevertheless, the recognition works well.

Here is a sample spectrogram that this algorithm generates:
![spectro](https://user-images.githubusercontent.com/4426185/97347735-3f402580-189e-11eb-8e9b-5b405f62ad13.png)

# `retryms`

Shazam API returns a `retryms` hint when there are no matches:
```json
{ "matches": [], "tagid": "34fe8632-7e6b-47c0-a5fa-1fedaa623c37", "retryms": 5000 }
{ "matches": [], "tagid": "34fe8632-7e6b-47c0-a5fa-1fedaa623c37", "retryms": 9000 }
{ "matches": [], "tagid": "34fe8632-7e6b-47c0-a5fa-1fedaa623c37", "retryms": 12000 }
{ "matches": [], "timestamp": 0, "tagid": "34fe8632-7e6b-47c0-a5fa-1fedaa623c37" }

```
It suggests to submit signatures for incrementally growing spectrograms. In other words, it allows up to 4 attempts before giving up.

Looks like they have multiple databases with different levels of detail, because popular songs are usually recognized faster.

**Comment by marin-m** [comment]
Hello,

>I wonder how you got to know the signature format. Is this the result of reverse engineering?

Part of the information needed for building the application was obtained by analyzing the mobile application, in respect to the  [Avis du Conseil d'état du 16 juillet 2008](https://www.legifrance.gouv.fr/ceta/id/CETATEXT000019216315/) which explicitly interprets the existing copyright exceptions related to software reverse engineering as applicable in the context of developing free software. However, according to the law, I may not be able to share much of the obtained information outside of the purpose of building my application.

>I don't use the 0.24 padding in the 'number of samples field', and it works, too. Are you sure that the factor is always 0.24 or it drifts?

The calculation is correct, although maybe it was not using a single float multiplication in the original code. However this was designed and verified to produce the same output as other clients.

>I found that peak detection can be as simple as scanning for the maximum magnitude within ±48 interval horizontally and vertically. I don't use spreading

This part of the code was designed to mimic as best as possible the behavior of the original client in order to ensure compatibility (applying some refactoring though).

>Shazam API returns a `retryms` hint when there are no matches:

Yes, the official clients tend to submit samples of different sizes depending on the obtained level of success, as it can be observed with a simple network capture software.

However, I implemented simple behavior with this application (as it seemed to be what worked the best, shorter windows gave erratic or sometimes erroneous results and signatures calculated on whole files were huge):
* When analyzing a single size, take the middle 12 seconds of it.
* When capturing from the microphone, use a sliding window of the last 12 seconds, submitted at a 4 second rate.

Regards,
