### ISSUE TITLE
Clarification Needed: "...manipulating data-URI audio fingerprints..."

### ISSUE THREAD

**Issue by hg2s** [marin-m/SongRec#68]
What is the significance of:

./songrec audio-file-to-fingerprint sound_file.mp3
./songrec fingerprint-to-recognized-song 'data:audio/vnd.shazam.sig;base64,...'

as described in the [ReadMe](https://github.com/marin-m/SongRec#readme)? 

-Thank you

**Comment by marin-m** [comment]
Hello,

An audio fingerprint is a binary-encoded list of frequency/time/amplitude peaks detected in the provided audio excerpt by the audio fingerprinting algorithm, and intended to be processed by Shazam's servers.

Data-URI is a standard format where arbitrary binary or text data is encoded to Base64, and then the Base64-encoded data is prefixed with "data:" followed with a MIME type and a comma. See: https://en.wikipedia.org/wiki/Data_URI_scheme

Here, the intend of executing these commands separately or in a row is to first perform offline generation of the data-URI encoded audio fingerprint of the provided sound excerpt, so that the user can choose to contact Shazam's servers and obtain a response in a JSON or other format separately, later, but also possibly with other settings, with an arbitrarily crafted data-URI fingerprint for test purposes, for debugging purposes, etc.

Regards,
